name: CD
on: [push]
jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f deploy/deployment.yaml
# for test
